# Generated by Django 3.1.7 on 2021-03-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210316_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.batch'),
            preserve_default=False,
        ),
    ]
