# Generated by Django 3.1.7 on 2021-03-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20210318_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='batch',
        ),
        migrations.AddField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.batch'),
            preserve_default=False,
        ),
    ]
